package com.jvcodingsolutions.echojournal.core.database.topic

import androidx.room.Entity
import androidx.room.PrimaryKey


// Since topic can only exist once in the DB it is also the primary key which is not autogenerated
@Entity
data class TopicEntity(
    @PrimaryKey(autoGenerate = false)
    val topic: String
)
